### ISSUE TITLE
Sunflower crashes when trying to delete other other users directory

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#149]
When trying to delete directory which belongs to root user, Sunflower crashes with following error:
````
*** Error in `/home/{$USER}/repositories/Sunflower/Sunflower.py': double free or corruption (fasttop): 0x00007fc50c001af0 ***
Failed running with python2.7
````
Tested with latest version from develop branch. Is there any way I could run Sunflower (e.g. debug mode) to get more detailed bug reports?

**Comment by MeanEYE** [comment]
This doesn't look like a Sunflower error at all. You could install `python-dev` package and then run Python with `gdb` and see where it crashes. Python errors always display file and line number where error occurred. Can you be more specific about directory you tried to remove? And do you have "delete to trash" enabled?

**Comment by joshas** [comment]
Yes, I had "Delete items to trashcan" enabled. After turning it off I get no crash when deleting - alert with permission error is displayed.
Running pyhton from gdb got no more information, bt command results in "No stack.". Using debug instructions from here: https://wiki.python.org/moin/DebuggingWithGdb
OS: Xubuntu 15.10 x86_64

**Comment by MeanEYE** [comment]
Oh wow, this bug is really hard to track. I did some research and it looks like its `glibc` bug you ran into by accident. Finding and reporting this bug might prove to be a challenge. It's certainly not Sunflower error and it occurs in specific function call by Python to GIO or at least I think so. If you try searching for "double free or corruption (fasttop)" you'll see this bug occurring in so many places it's not even funny. It might be also a rather generic error message, but that's as much information as we have to go on.

It does seem to be fixed in newer versions and I do have problems reproducing this issue on Debian Testing. So I suggest waiting for update. Sadly there's nothing I can do prevent this bug from happening as I can't predict the crash nor catch and exception so I'll be forced to close this and hope for upstream developers to fix it for you.
