### ISSUE TITLE
wiki page or any documentation with shortcuts, shortcuts in menu

### ISSUE THREAD

**Issue by nbbn** [MeanEYE/Sunflower#196]
Hello,
http://sunflower-fm.org/ has statement:
Keyboard oriented Fully optimized for keyboard users.

Is there any documentation or menu position with all shortcuts? I don't think so.
I founded https://code.google.com/archive/p/sunflower-fm/wikis/KeyboardShortcuts.wiki but it's probably outdated, ugly, and not comprehensive.

What is more, shortcuts in menu, that would be great!
![shortcuts](https://i.stack.imgur.com/vEIpn.png)

**Comment by MeanEYE** [comment]
You can pretty much view all the shortcuts in _Preferences_ under _Key bindings_. For some strange reason, GTK+ doesn't like showing shortcuts like you pointed out on the screen shot when menu items are created through commands, even though they work perfectly fine. Since next version is designated to be GTK3 this issue might be easier to fix so I'll tag this issue as a bug and we'll see if it's easier to handle.

**Comment by joshas** [comment]
Gnome Files has nice "Keyboard Shortcuts" window:
![shortcuts](https://user-images.githubusercontent.com/79141/60993775-cab73f80-a357-11e9-8334-22c1e43c8a69.png)

Maybe we could implement something similar in Sunflower, with shortcuts list generated dynamically from user Preferences.

**Comment by MeanEYE** [comment]
We can but I don't know if this window would suffice as we have many many more shortcuts.

**Comment by joshas** [comment]
Single window with predefined most important hotkeys could be very useful for new users, as menu entries doesn't have hotkeys listed any more.

**Comment by MeanEYE** [comment]
Agreed.
