### ISSUE TITLE
A crash during deleting a folder without permissions

### ISSUE THREAD

**Issue by nervgh** [MeanEYE/Sunflower#197]
Hi

It is another issue =)

I use the **Ubuntu 15.10.** My file system is **ext4**.
I launch the Sunflower as a user with 1000 identifier.
If I try to remove a folder without permission the Sunflower crashes.

I made a [video](https://drive.google.com/file/d/0B2CP8LcWJSNSY24tRU5NcF9GZ1U) for you.

**Comment by MeanEYE** [comment]
Thanks. I think this is the same issue as the one with removing trash directory. Basically we fail miserably at handling any sort of errors during removal.

**Comment by cmallwitz** [comment]
My fix for issue 194 seems to fix this issue as well.

My test steps:
- in a normal (writable) directory, create a sub-directory and another file in it
- make both file and directory read only (chmod -x)
- attempt to delete sub-directory 
- I get an error message (about permission issue on the test file in the sub-directory) and the option to try to move it to waste-bin
- trying that I get another error message - now skipping the whole operation and I'm left were I started
- no crash and funny business with hanging process bars/dialogues
- this sound like the expected behaviour to me...

Question: one could argue that initial failed delete on the file should not try to move the file itself to waste bin but rather the whole sub-directory which would succeed in this case - but that would be a request for an improvement I guess...

Any thoughts?

**Comment by nervgh** [comment]
@cmallwitz  thanks for your response.

> but that would be a request for an improvement I guess

Yes. I think the Sunflower need to say something like "No permission". The Nautilus uses that way.

**Comment by MeanEYE** [comment]
@cmallwitz can you confirm this is fixed with your pull request?

**Comment by cmallwitz** [comment]
Confirmed - after pulling latest code from branch develop and going through the steps above, everything is working as expected

**Comment by MeanEYE** [comment]
Thanks. I'll close the issue.
