### ISSUE TITLE
GTK3 - local file monitoring not working for moved/renamed files

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#208]
With the move to GTK3 we started to set up our Gio monitors like this:
   Gio.File.new_for_path(path).monitor(Gio.FileMonitorFlags.SEND_MOVED)

The problem is that in the past, we haven't asked for it and Sunflower doesn't actually contain code (in file_list.py) to handle MOVED events - result: moved /renamed field disappear from file list.

Should we use Gio.FileMonitorFlags.NONE (this sends separate DELETED and CREATED events) or should we add logic to handle MOVED events (probably more efficient)?

I've tried NONE and this would restore previous functionality (not loosing moved/renamed files).

**Comment by MeanEYE** [comment]
We have [poor solution](https://github.com/MeanEYE/Sunflower/blob/develop/application/plugins/file_list/file_list.py#L1397-L1398) which is a nasty patch to get around missing `MOVED` event. I would prefer to have `MOVED` instead of `DELETE` + `CREATE`. Mind you, this issue is also present when file is saved by some applications which also sends `CREATE` for some reason. So don't remove anything yet without extensive testing.

**Comment by cmallwitz** [comment]
I'm not sure I made myself clear - the problem isn't us missing MOVED events. We receive them as requested but we don't have code to handle them and because of it renamed files disappear from the file panel.

**Comment by MeanEYE** [comment]
You did make yourself clear. We need to handle `MOVED` events.

**Comment by cmallwitz** [comment]
Resolved
