### ISSUE TITLE
GTK3 - using header_bar on Gtk.Dialog assumes GTK >= 3.12.0

### ISSUE THREAD

**Issue by cmallwitz** [MeanEYE/Sunflower#219]
Using header_bar with with Gtk.Dialog requires GTK >= 3.12.0 - breaking under Ubuntu 14.04 (most current LTS as of today)

**Comment by MeanEYE** [comment]
Hm. Then we should have an option. Using header bar or not matters very little in Sunflower as we use dialog functions the proper way, so if header bar is not available we just use regular action bar.

**Comment by cmallwitz** [comment]
Adding a check for header bars and then sprinkle the code with if: else: is akward. Sould we introduce another class layer for dialogs to abstract the issue away?

**Comment by MeanEYE** [comment]
Input dialogs themselves are abstract enough. I don't think we should go more abstract than that. Pretty much all dialogs inherit `InputDialog`.

**Comment by cmallwitz** [comment]
1) Quite a few classes in input_dialog.py don't inherit from InputDialog.
2) DeleteDialog & CopyDialog are messing around with header bar directly on
top of requesting it.

Without header bar support none of the dialogs defined can be created - I
get stack traces all coming down to:

  File
"/home/christian/tech/IdeaProjects/Sunflower_develop/application/gui/input_dialog.py",
line 31, in __init__
    self._dialog = Gtk.Dialog(parent=application, use_header_bar=True)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 500, in
__init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line
175, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line
175, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: gobject `GtkDialog' doesn't support property `use_header_bar'

Or similar e.g. for CopyDialog...

Some abstraction is required.

Christian

**Comment by MeanEYE** [comment]
You are right about `CopyDialog` but that's on purpose. But they "mess" with it in a rather generic way. Namely adding button for saving default configuration. I feel that can easily be implemented with old and new methods. Other classes which don't implement InputDialog are most likely those for overwritting, and they also have some inheritance.

In my opinion it would be better to just add conditions in those few places instead of increasing complexity of inheritance tree by adding another class for the sake of condition. Keeping the structure relatively flat I feel we are much more flexible and easier to get involved with, not to mention ease of maintenance.

**Comment by cmallwitz** [comment]
Resolved
