### ISSUE TITLE
Do not show cursor in inactive pane

### ISSUE THREAD

**Issue by tssk** [MeanEYE/Sunflower#241]
Do not draw (or visually differentiate) cursor in the pane that is not active.

Now it is confusing to easily guess which pane i active (highlighted heading of pane does not help in this way as the visual focus is on the pane content).

Thanks.

P.S. I am absolutelly thrilled to finaly find usable GTK two pane file manager.

**Comment by MeanEYE** [comment]
This issue is hard to fix in GTK2 version of the program without modifying the theme itself or making a custom render function for the whole list which will end up being too expensive.

However, this is really easy to fix in GTK3 version of the program and in fact has been fixed (see #192). Next version of Sunflower will be in GTK3 and will have this patch included. Thanks for reporting!
