### ISSUE TITLE
[ENH] Un-highlight file in non-active tab

### ISSUE THREAD

**Issue by icapan** [MeanEYE/Sunflower#271]
let me explain by a photo:
![sunflower-fm-tabs](https://cloud.githubusercontent.com/assets/10756983/24841901/341114a2-1d8f-11e7-8813-9166a91ddeab.png)
Left tab is active, and right isn't. When I press delete, it is not trivial to figure out what file will be deleted, lspcmcia or chown. What I want: unhighlight file "chown" in right window until focus comes to it. 
Why I went to all this trouble submitting this: I just killed a large directory, because I started a delete process in wrong tab. And it wasn't the first time it happened to me. 
Second issue: opening archived files with file listing inside Sunflower. But it was probably already requested many times.

Pozdrav iz HR!

**Comment by Taomach** [comment]
Yes, that mildly bugged me for a long time. Good idea.

**Comment by icapan** [comment]
Well, version 02(59) on Ubuntu 14.04 doesn't have that problem.

**Comment by MeanEYE** [comment]
This is a theming issue. New version 0.4 already has this issue solved. Since GTK3 uses CSS it's easy to solve it instead of making custom rendering and color modifications. With previous version of GTK this wasn't as easy and required modifying some properties which usually resulted in broken compatibility later down the line.

Thanks for reporting it and sorry for the slow arrival of 0.4. :)
Pozdrav!
