### ISSUE TITLE
file list panel font size

### ISSUE THREAD

**Issue by r91085** [MeanEYE/Sunflower#292]
I can change the font size of terminal panel , but I don't find this setting of file list panel .
Does it exist ?

**Comment by MeanEYE** [comment]
There is. It's located in Preferences window.

![screenshot from 2018-03-22 09-56-31](https://user-images.githubusercontent.com/1911594/37757967-53b8582c-2db7-11e8-8e5d-7c0b05fd614a.png)

**Comment by thenoobtester** [comment]
Hi,

I have the same issue. What do you have to put exactly in the font column? When I double-click I get the possibility to increase a numeric value but it doesn't work I get in the console:

`  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 274, in set_value
    (py_value, type(py_value)))
ValueError: Expected string but got 4<class 'int'>
`

**Comment by thenoobtester** [comment]
By changing lines 599 and 645 in /usr/lib/python3/dist-packages/sunflower/gui/preferences/item_list.py from

```
self._columns_store.append((column, size, is_visible, font_size)
self._columns_store.append((column, size, is_visible, "'" + str(font_size) + "'"))

And

self._columns_store.set_value(selected_iter, Column.FONT_SIZE, new_size )
self._columns_store.set_value(selected_iter, Column.FONT_SIZE, "'" + str(new_size) + "'")
```

Don't judge I'm not a programmer :) But it works.

**Comment by thenoobtester** [comment]
Awesome file manager by the way, does it support colored folders (gvfs-set-attribute metadata::custom-icon)?

Thank you

**Comment by thenoobtester** [comment]
Also row-hinting doesn't work, I read GTK3 doesn't support it anymore, it is true? If that's the case is there a way to color the rows?

**Comment by MeanEYE** [comment]
> Hi,
> 
> I have the same issue. What do you have to put exactly in the font column? When I double-click I get the possibility to increase a numeric value but it doesn't work I get in the console:
> 
> ` File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 274, in set_value (py_value, type(py_value))) ValueError: Expected string but got 4<class 'int'>`

This is an issue which was fixed at some point. Sadly I didn't get to release a version since. Am kind of hoping to finish mount managers before doing so but releasing often is probably a better idea.

> Also row-hinting doesn't work, I read GTK3 doesn't support it anymore, it is true? If that's the case is there a way to color the rows?

Sadly, yes this is true. I kept the option in hopes of achieving it through CSS, but they have removed that as well. Only way to achieve it now is to completely redo rendering methods of TreeView component which is too much effort for such simple functionality.

> Awesome file manager by the way, does it support colored folders (gvfs-set-attribute metadata::custom-icon)?
> 
> Thank you

Thank you. Custom icons use to work. Am not sure if that's still the case considering they also use to support emblems and that got removed as well. That said I did implement emblems again, but they are only local to application since Nautilus removed support for them. Hopefully emblems make up for lack of colored folders and perhaps custom icons.

**Comment by thenoobtester** [comment]
Thanks for the clarifications :)

**Comment by MeanEYE** [comment]
You are welcome. I'll try to push new version out as soon as possible. Perhaps releasing it a bit unfinished is better so people can help me find issues. Next version is sure to be 1.0 finally.
