### ISSUE TITLE
Breadcrumb navigation styling issues on Ubuntu 19.04 (Beta)

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#327]
On Ubuntu 19.04 (Beta) breadcrumb navigation bar has no "active" style and selected directory title is displayed in white color, making it impossible to read.
![ubuntu-breadcrumbs](https://user-images.githubusercontent.com/79141/55901687-85f20000-5bd2-11e9-8268-17870feac35c.png)

Compared to Sunflower screenshot in README.md active panel should have breadcrumbs bar highlighted and active directory text should be dark.

This might be an issue with new Ubuntu theme "yaru". If that's the case, I could report issue to them.

**Comment by MeanEYE** [comment]
Ah this makes sense. Basically it's a fault in Ubuntu theme, but we can't really expect them to fix ti for our sake. To achieve breadcrumbs we add classes `linked` and `path-bar` to horizontal box containing buttons. Ideally these classes should set behavior and some looks but not set colors, since colors can be inherited. Ubuntu theme however sets font color as well.

If you wish you can try and tackle this one. There's `sunflower/styles/main.css` file which contains additional styles for Sunflower that slightly modify theme behavior. New entry should be made for breadcrumb buttons and change font color to standard theme button color.

Starting Sunflower with GTK+ introspection tool can be done by running `GTK_DEBUG=interactive python3 -m sunflower`.

**Comment by joshas** [comment]
Creating style overrides will only add technical debt in the future and probably break other GTK themes. I'd suggest waiting until Yaru fixes it in their theme https://github.com/ubuntu/yaru/issues/1351, as other GTK themes probably doesn't have this issue with path-bar styles anyway.
Or we could create fully custom style for breadcrumbs that does not depend on theme implementation.

**Comment by MeanEYE** [comment]
You are right, it's only going to complicate things should we try to fix this. Thanks for opening the issue on Ubuntu's theme repository.

**Comment by joshas** [comment]
After https://github.com/MeanEYE/Sunflower/commit/87c5ed51bd4b8c068f227c8c561b5ac340b94ff1 breadcrumbs look good on Ubuntu 19.04:

Yaru
![ubuntu-yaru](https://user-images.githubusercontent.com/79141/60990426-13b7c580-a351-11e9-8aa7-18bb953c67d4.png)

Yaru dark
![ubuntu-yaru-dark](https://user-images.githubusercontent.com/79141/60990434-15818900-a351-11e9-8d16-ad23b555dea5.png)

Might need active color tweaking for better contrast on Adwaita-dark though, but it is not in scope of this issue.
![adwaita-dark](https://user-images.githubusercontent.com/79141/60990569-62fdf600-a351-11e9-8f9a-70efeab7f34d.png)
