### ISSUE TITLE
Filename truncated upon opening file containing hash symbol

### ISSUE THREAD

**Issue by Udo-S** [MeanEYE/Sunflower#330]
If a file listed in Sunflower contains a hash symbol (e.g. my_file#14.pdf) opening that file by double click or right click+open fails because the filename is truncated at the hash symbol (rest is treated as a comment). Thus an incomplete filename is passed to the linked application (e.g. PDF viewer). Sunflower 0.3 (61)

**Comment by MeanEYE** [comment]
Thanks for reporting this issue. Path handling in Sunflower leaves a lot to be desired and I plan on unifying approach in how we treat them.

**Comment by joshas** [comment]
Duplicate of #183

**Comment by joshas** [comment]
Looks like issue with hash symbols was fixed some time ago in develop branch. I cannot reproduce it.
@Udo-S could you test latest Sunflower version from develop branch?

**Comment by Udo-S** [comment]
Tried to test with develop branch, but there is no file "Sunflower.py" in that branch. Is that OK?

**Comment by MeanEYE** [comment]
It is. You can start it with `python3 -m sunflower` from the repository root.

**Comment by Udo-S** [comment]
OK, before I had 0.3 (61), now I have 0.4 (62) from the develop branch. The issue with the # in filenames is now working. But now
- I can't copy/move files from one pane to the other using the mouse.
- There's no traditional menu anymore
- Using different background colors for consecutive lines is not working (appearence preference)

**Comment by MeanEYE** [comment]
There are plenty of issues with 0.4. First two are known. Third one I am not aware of so opening a new issue would be most welcome. Are you referring to the alternating background color?

**Comment by MeanEYE** [comment]
Just to confirm, you can't reproduce this issue with file names being truncated with hash symbol?

**Comment by Udo-S** [comment]
Are you referring to the alternating background color? -- Yes, I'm referring to this!
Just to confirm, you can't reproduce this issue with file names being truncated with hash symbol? -- Yes, it's fixed.
Third one I am not aware of so opening a new issue would be most welcome. -- I leave that up to you.
Are you doing a complete redesign in develop? Or why are we facing so many regressions?

**Comment by MeanEYE** [comment]
We are switching from GTK2 to GTK3 but along the way switched to Python3 as well, since Python2 is getting phased out. Some regressions come from Py3 switch, some from GTK3 switch.

As for why we are doing those, simply put old stuff is no longer maintained. PyGTK module which was previously used was abandoned and is only on life-support. Developers suggested switching to GObject Introspection based approach. This is the source of more regressions as GI works the way GTK+ is designed to work, while PyGTK worked the way its developers thought GTK+ worked.

All in all, issues are not serious, but they are plentiful. In summary switch was an excellent thing since GTK3 was stabilized in version 3.20, which Sunflower is targeting. We gained a lot of performance, simpler and cleaner UI, became future-proof, Wayland became supported display protocol, etc.

Long pause between releases is not indicative of these issues, merely my semi-absence due to work eating me alive. But thanks to @joshas and some other people who started contributing recently am getting more involved in it again.

**Comment by MeanEYE** [comment]
Oh, also, it's not a complete redesign, but it is seeing a lot of improvement. Popovers are a wonderful thing we didn't have in previous version of GTK+ and am using them extensively. They are much more flexible and allow us to simplify code.

![image](https://user-images.githubusercontent.com/1911594/60769477-8a925b80-a0d0-11e9-9eb8-a439383df4e7.png)
For example new locations menu is more intuitive and easier to look at, as opposed to standard menu that popped up previously. This new locations menu also replaces both history, bookmarks and few other windows but provides more benefits.
