### ISSUE TITLE
Opening archive breaks breadcrumbs

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#332]
After opening zip archive, navigating inside and going up to parent directory, leaves breadcrumbs in broken state: first item contains path to directory:
![archive-breadcrumbs](https://user-images.githubusercontent.com/79141/60364052-e16fa500-99ed-11e9-9362-39e802ec691d.png)

To fix it you have to go into child directory.

**Comment by MeanEYE** [comment]
Thanks. Breadcrumbs are in dire need of some attention. I'll fix this up.

**Comment by joshas** [comment]
Continuing conversation from #406 about fixing breadcrumbs path inside archive.

Problem is probably here, as this function returns full path to archive as root path:
https://github.com/MeanEYE/Sunflower/blob/20072f76ae8a364398c68ed5ea1d0f80de3c7adb/sunflower/plugins/archive_support/zip_provider.py#L245-L247

Naive fix would be to change get_root_path result to `os.path.sep` that always returns root. But what other cases there might be, that this function should be aware of? Archive opened from FTP? From trash list? From another archive?

**Comment by MeanEYE** [comment]
Aaah, okay. That makes sense now. Basically what's happening is that "get_root_path" is hardcoded in breadcrumbs as `/`. That's why it looks like that. There are many different cases where root path will be different from usual `/`. From GVFS to user space mounts, medias, custom providers like WebDAV, etc.

**Comment by joshas** [comment]
So what would be the best way to get root path here? Could we use pathlib, as none of os.path functions seem to fit without additional string manipulation.

**Comment by MeanEYE** [comment]
Breadcrumbs should show full root path instead of hard coded `/`. But once root of current provider is reached we should display path as different provider would see it. That is current behavior as can be seen by icon for the path menu, except when reaching the root of current provider breadcrumbs are not updated to reflect that. Not sure why this is the case.
