### ISSUE TITLE
Opening directory with many files temporary freezes UI

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#415]
After entering directory with lots of files or folders, e.g. node_modules, UI freezes for a second or two. Isn't directory reading handled in separate thread? Problem occurs only opening directory first time after Sunflower was restarted, all subsequent returns to same directory doesn't freeze UI.

**Comment by MeanEYE** [comment]
Yes, this is an issue I noticed as well. Loading of directory data is handled in separate thread but loading of items isn't. Initially this didn't seem like a problem and I thought we could get away with it since large majority of loading time goes to additional information. I planned on fixing this for next version.

**Comment by MeanEYE** [comment]
This should have been addressed by the fix I pushed out today. I can't completely eliminate the freeze since populating thousands of entries and having them sorted takes time but loading times are considerably shorter now. Please retest and let me know if there's more that needs fixing.

**Comment by joshas** [comment]
Just compared version before fix and after - the delay when UI is frozen and file list becomes empty is gone.
