### ISSUE TITLE
Sort order is incorrect for numbers

### ISSUE THREAD

**Issue by MikeWallaceDev** [MeanEYE/Sunflower#85]
Files are incorrectly sorted when the name includes a number as can be seen in this screenshot

![screenshot_005](https://cloud.githubusercontent.com/assets/5375835/6925928/f53b81e8-d7b0-11e4-8e40-282ccd4011fc.png)

**Comment by MeanEYE** [comment]
Thanks for reporting this. We have an option to enable that behavior. Go to _Edit -> Preferences_ then click on _Item list_ tab. Select _Operation_ and make sure _Number sensitive item sorting_ is checked. I made this as an option because it usually takes more CPU time to interpret string as number and then sort accordingly. It's not a big difference, but I left it as an option for user.

**Comment by MikeWallaceDev** [comment]
Got it, thanks!  Sorry for reporting this, I just never saw that as an option.  So I admit that I didn't even look for it...

**Comment by MeanEYE** [comment]
Not big of an issue really. Perhaps am overdoing it with options. I still think customization and sane defaults are the right way to go.
