### ISSUE TITLE
Fast media preview thumbnails not in '.cache/thumbnails'

### ISSUE THREAD

**Issue by bfx** [MeanEYE/Sunflower#92]
When enabled the Fast media preview, the thumbnails seems generated in the ~/.thumbnails.

**Comment by MeanEYE** [comment]
This is probably due to using Gnome 2 thumbnail factory. I don't really specify where thumbnails are stored. Nautils and others have probably moved to using newer version of library which is not an option for me considering `python-gnome2` is no longer developed. This issue however will be automatically solved once we switch to GTK3.

**Comment by MeanEYE** [comment]
This is no longer an issue with GTK3 migration.
